vse: &vse
  docker:
    - image: circleci/node:8.11.3
ansible:
  docker: &ansible
    - image: 'circleci/python:latest'
      environment:
        ANSIBLE_HOST_KEY_CHECKING: no

version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     docker: *ansible
     steps:
        - attach_workspace:
           at: .
        - ansible-playbook/install
        - run:
           command: sudo pip install ansible boto boto3
        - add_ssh_keys:
           fingerprints:
            - "37:8a:2f:fa:62:de:14:4f:99:a4:0d:62:5f:be:71:f1"
        - ansible-playbook/playbook:
            playbook: ./ansible/ec2_deploy.yml
            playbook-options: --user ubuntu
            
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: main
